- hosts: all
  vars_files:
   - "{{ ansible_facts['distribution'] }}.yml"

  tasks:
   - name: installing webserver software through their respective service
     package: 
      name: "{{ package_name }}"
      state: present

   - name: copying the webpage
     template: 
       dest: "{{ doc_root }}"
       src: index.html.j2
              
   - name: starting the service
     service: 
       name: "{{ service_name }}"
       state: started    
